import { type ProjectApi } from '../types';

const API = 'http://localhost:3000/api/projects';

// Generated by https://quicktype.io

export const getAllProjects = async (token: string): Promise<ProjectApi> => {
  const response = await fetch(`${API}`, {
    method: 'GET',
    headers: {
      // eslint-disable-next-line prettier/prettier
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
    },
  });

  const data = await response.json();

  return data;
};
